# Generated by Django 4.1.5 on 2023-04-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="img_check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_image",
                    models.ImageField(blank=True, null=True, upload_to="image_check/"),
                ),
                ("disease_name", models.CharField(max_length=200)),
            ],
        ),
    ]
